### PR TITLE
App wrapper setup bugfix

### PR DESCRIPTION
**Pull request by jstucke**
Fixed a bug that was introduced in #867 that was causing an exception in the flask app wrapper module during startup
```python
Traceback (most recent call last):
  File "flask_app_wrapper.py", line 56, in <module>
    web_interface = create_web_interface()
  File "flask_app_wrapper.py", line 51, in create_web_interface
    setup_logging(config, args, component='frontend')
  File "src/./helperFunctions/program_setup.py", line 89, in setup_logging
    log_file = get_log_file_for_component(component)
  File "src/./helperFunctions/program_setup.py", line 104, in get_log_file_for_component
    log_file = Path(cfg.logging.logfile)
AttributeError: 'NoneType' object has no attribute 'logging'
```

Also refactored the `start_fact.py` script which e.g. used `global`

### CODE REVIEW

File: src/update_statistic.py [hunk 1]
```diff
@@ -29,7 +29,7 @@
 def main(command_line_options=None):
     if command_line_options is None:
         command_line_options = sys.argv
-    _, config = program_setup(PROGRAM_NAME, PROGRAM_DESCRIPTION, command_line_options=command_line_options)
+    _ = program_setup(PROGRAM_NAME, PROGRAM_DESCRIPTION, command_line_options=command_line_options)
```
Comment (rhelmke) [inline src/update_statistic.py:32]:
```suggestion
    program_setup(PROGRAM_NAME, PROGRAM_DESCRIPTION, command_line_options=command_line_options)
```

(maybe?)

**Review by rhelmke — APPROVED** [review]
